CREATE TABLE brand_reputation (
                                  id BIGSERIAL PRIMARY KEY,
                                  brand_name VARCHAR(100) NOT NULL UNIQUE,
                                  score DOUBLE PRECISION NOT NULL CHECK (score >= 0 AND score <= 10),
                                  tier VARCHAR(20) NOT NULL,
                                  notes VARCHAR(255),
                                  created_at TIMESTAMP DEFAULT NOW(),
                                  updated_at TIMESTAMP DEFAULT NOW()
);

INSERT INTO brand_reputation (brand_name, score, tier, notes) VALUES
                                                                  ('Optimum Nutrition',   9.5, 'TOP',     'Globalni lider, treća strana testiranje'),
                                                                  ('Scitec Nutrition',    8.5, 'TOP',     'Evropski lider, odlična transparentnost'),
                                                                  ('MyProtein',           8.0, 'TOP',     'Veliki izbor, dobra cena/kvalitet'),
                                                                  ('Dymatize Nutrition',  8.5, 'TOP',     'ISO100 među najboljim izolatima'),
                                                                  ('Rule 1',              8.0, 'TOP',     'Minimalni aditivi, čist sastav'),
                                                                  ('Now Foods',           8.0, 'TOP',     'Clean label, pouzdan'),
                                                                  ('USN',                 7.5, 'MID',     'Poznat brend, solidna formula'),
                                                                  ('BioTech USA',         7.5, 'MID',     'Madjarski brend, popularan u regionu'),
                                                                  ('Amix Nutrition',      7.5, 'MID',     'Češki brend, dobar kvalitet'),
                                                                  ('Jarrow Formulas',     7.5, 'MID',     'Dobar kvalitet, manje poznat'),
                                                                  ('Yamamoto Nutrition',  7.5, 'MID',     'Italijanski brend, popularan u regionu'),
                                                                  ('Kevin Levrone',       7.0, 'MID',     'Poznat brend, dobra distribucija'),
                                                                  ('Weider',              7.0, 'MID',     'Dugogodišnji brend, pouzdan'),
                                                                  ('PhD Nutrition',       7.0, 'MID',     'UK brend, dobar kvalitet'),
                                                                  ('Applied Nutrition',   7.0, 'MID',     'Rastući brend, dobra vrednost'),
                                                                  ('MuscleTech',          7.0, 'MID',     'Poznat, ali složeni sastavi'),
                                                                  ('BSN',                 7.0, 'MID',     'Dobar ukus, solidna formula'),
                                                                  ('Cellucor',            7.0, 'MID',     'C4 brend, poznat u regionu'),
                                                                  ('Universal Nutrition', 7.0, 'MID',     'Klasičan brend, pouzdan'),
                                                                  ('Nutriversum',         7.0, 'MID',     'Madjarski brend, dobar kvalitet'),
                                                                  ('Reflex Nutrition',    7.0, 'MID',     'UK brend, solidan'),
                                                                  ('Biotech',             7.5, 'MID',     'Alias za BioTech USA'),
                                                                  ('Mutant',              6.5, 'MID',     'Kanada, agresivan marketing'),
                                                                  ('GNC',                 6.5, 'MID',     'Retail brend, prosečan kvalitet'),
                                                                  ('QNT',                 6.5, 'MID',     'Belgijski brend, prosečan'),
                                                                  ('DY Nutrition',        6.5, 'MID',     'Dorian Yates brend'),
                                                                  ('IRONMAXX',            6.5, 'MID',     'Nemački brend, solidan'),
                                                                  ('Barebells',           7.0, 'MID',     'Švedski brend, poznat po ukusu'),
                                                                  ('Basic Supplements',   6.0, 'LOW',     'Lokalni brend, manje poznat'),
                                                                  ('The Nutrition',       6.0, 'LOW',     'Lokalni brend'),
                                                                  ('Ultimate Nutrition',  6.5, 'MID',     'Američki brend, solidan'),
                                                                  ('Maximalium',          6.0, 'LOW',     'Lokalni brend, manje poznat'),
                                                                  ('PurePro',             6.0, 'LOW',     'Manje poznat brend'),
                                                                  ('Starlabs',            6.0, 'LOW',     'Manje poznat brend'),
                                                                  ('Naughty Boy',         6.5, 'MID',     'UK brend, rastući'),
                                                                  ('BLADE SPORT',         6.0, 'LOW',     'Manje poznat brend');