ALTER TABLE products
    ADD COLUMN IF NOT EXISTS primary_weight_grams DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS sugar_per_100g DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS fat_per_100g DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS calorie_per_100g DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS protein_source VARCHAR(50);