package com.proteinoteka.analytics;

public enum DecisionFlag {
    EMAIL_PROBLEM_SUBJECT_OR_TIMING,
    SCALE_EMAIL_CAMPAIGN,
    CTA_OR_VALUE_PROPOSITION_PROBLEM,
    HIGH_PERFORMING_EMAIL,
    UX_FRICTION_MODAL_FLOW,
    UX_TOO_SLOW,
    AUDIENCE_MISMATCH,
    SYSTEM_RELIABILITY_ISSUE,
    STRONG_RETENTION_SIGNAL
}
