// GENERATED by ops/price-report/build.py from a read-only production query - do not edit by hand.
// Deliberately contains no store names: the published report describes the market, not individual shops.
// A dated edition of the price report: the numbers below describe the window, not today's prices.
export const REPORT_2026_09 = {
  "edition": "2026-09",
  "baseline": "2026-06-24",
  "end": "2026-09-19",
  "panelStoreCount": 5,
  "excludedStoreCount": 1,
  "panelTotal": 271,
  "used": 232,
  "dropped": {
    "stale": 9,
    "unstable": 2,
    "excludedStore": 28
  },
  "overall": {
    "n": 232,
    "up": 40,
    "down": 1,
    "same": 191,
    "mean": 2.4,
    "median": 0.0,
    "riserMean": 14.4,
    "fallerMean": -29.6,
    "meanRobust": 2.2
  },
  "categories": [
    {
      "n": 111,
      "up": 22,
      "down": 1,
      "same": 88,
      "mean": 2.9,
      "median": 0.0,
      "riserMean": 15.9,
      "fallerMean": -29.6,
      "key": "whey_concentrate",
      "meanRobust": 2.7
    },
    {
      "n": 43,
      "up": 7,
      "down": 0,
      "same": 36,
      "mean": 3.2,
      "median": 0.0,
      "riserMean": 19.4,
      "fallerMean": 0.0,
      "key": "whey_isolate",
      "meanRobust": 3.0
    },
    {
      "n": 33,
      "up": 3,
      "down": 0,
      "same": 30,
      "mean": 0.9,
      "median": 0.0,
      "riserMean": 9.6,
      "fallerMean": 0.0,
      "key": "vegan",
      "meanRobust": 0.9
    },
    {
      "n": 27,
      "up": 6,
      "down": 0,
      "same": 21,
      "mean": 1.1,
      "median": 0.0,
      "riserMean": 5.0,
      "fallerMean": 0.0,
      "key": "blend",
      "meanRobust": 0.8
    },
    {
      "n": 9,
      "up": 0,
      "down": 0,
      "same": 9,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "key": "casein",
      "meanRobust": 0.0
    },
    {
      "n": 9,
      "up": 2,
      "down": 0,
      "same": 7,
      "mean": 3.8,
      "median": 0.0,
      "riserMean": 17.1,
      "fallerMean": 0.0,
      "key": "other",
      "meanRobust": 2.2
    }
  ],
  "brands": [
    {
      "n": 15,
      "up": 14,
      "down": 0,
      "same": 1,
      "mean": 8.5,
      "median": 6.7,
      "riserMean": 9.1,
      "fallerMean": 0.0,
      "brand": "Maximalium",
      "max": 20.1
    },
    {
      "n": 4,
      "up": 3,
      "down": 0,
      "same": 1,
      "mean": 11.6,
      "median": 8.8,
      "riserMean": 15.5,
      "fallerMean": 0.0,
      "brand": "5 Stars",
      "max": 28.9
    },
    {
      "n": 5,
      "up": 3,
      "down": 0,
      "same": 2,
      "mean": 1.9,
      "median": 2.0,
      "riserMean": 3.1,
      "fallerMean": 0.0,
      "brand": "Naughty Boy",
      "max": 4.8
    },
    {
      "n": 13,
      "up": 7,
      "down": 0,
      "same": 6,
      "mean": 13.8,
      "median": 18.2,
      "riserMean": 25.7,
      "fallerMean": 0.0,
      "brand": "Nutriversum",
      "max": 38.5
    },
    {
      "n": 4,
      "up": 2,
      "down": 0,
      "same": 2,
      "mean": 8.0,
      "median": 4.4,
      "riserMean": 16.0,
      "fallerMean": 0.0,
      "brand": "Amix Nutrition",
      "max": 23.3
    },
    {
      "n": 5,
      "up": 2,
      "down": 0,
      "same": 3,
      "mean": 10.4,
      "median": 0.0,
      "riserMean": 26.0,
      "fallerMean": 0.0,
      "brand": "Optimum Nutrition",
      "max": 34.4
    },
    {
      "n": 16,
      "up": 3,
      "down": 0,
      "same": 13,
      "mean": 3.1,
      "median": 0.0,
      "riserMean": 16.5,
      "fallerMean": 0.0,
      "brand": "QNT",
      "max": 22.1
    },
    {
      "n": 6,
      "up": 1,
      "down": 0,
      "same": 5,
      "mean": 3.6,
      "median": 0.0,
      "riserMean": 21.8,
      "fallerMean": 0.0,
      "brand": "PhD Nutrition",
      "max": 21.8
    },
    {
      "n": 6,
      "up": 1,
      "down": 0,
      "same": 5,
      "mean": 4.2,
      "median": 0.0,
      "riserMean": 25.4,
      "fallerMean": 0.0,
      "brand": "The Nutrition",
      "max": 25.4
    },
    {
      "n": 11,
      "up": 1,
      "down": 0,
      "same": 10,
      "mean": 0.2,
      "median": 0.0,
      "riserMean": 1.9,
      "fallerMean": 0.0,
      "brand": "BioTech USA",
      "max": 1.9
    },
    {
      "n": 22,
      "up": 0,
      "down": 0,
      "same": 22,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "brand": "Ultimate Nutrition",
      "max": 0.0
    },
    {
      "n": 10,
      "up": 0,
      "down": 0,
      "same": 10,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "brand": "OstroVit",
      "max": 0.0
    },
    {
      "n": 9,
      "up": 0,
      "down": 0,
      "same": 9,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "brand": "USN",
      "max": 0.0
    },
    {
      "n": 9,
      "up": 0,
      "down": 0,
      "same": 9,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "brand": "ExtriFit",
      "max": 0.0
    },
    {
      "n": 8,
      "up": 0,
      "down": 0,
      "same": 8,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "brand": "Scitec Nutrition",
      "max": 0.0
    },
    {
      "n": 7,
      "up": 0,
      "down": 0,
      "same": 7,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "brand": "BATTERY",
      "max": 0.0
    },
    {
      "n": 7,
      "up": 0,
      "down": 1,
      "same": 6,
      "mean": -4.2,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": -29.6,
      "brand": "Reflex Nutrition",
      "max": 0.0
    },
    {
      "n": 7,
      "up": 0,
      "down": 0,
      "same": 7,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "brand": "Basic Supplements",
      "max": 0.0
    },
    {
      "n": 7,
      "up": 0,
      "down": 0,
      "same": 7,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "brand": "Tesla Nutrition",
      "max": 0.0
    },
    {
      "n": 6,
      "up": 0,
      "down": 0,
      "same": 6,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "brand": "Applied Nutrition",
      "max": 0.0
    },
    {
      "n": 5,
      "up": 0,
      "down": 0,
      "same": 5,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "brand": "Vitalikum",
      "max": 0.0
    },
    {
      "n": 4,
      "up": 0,
      "down": 0,
      "same": 4,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "brand": "DY Nutrition",
      "max": 0.0
    },
    {
      "n": 4,
      "up": 0,
      "down": 0,
      "same": 4,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "brand": "Genius Nutrition",
      "max": 0.0
    },
    {
      "n": 4,
      "up": 0,
      "down": 0,
      "same": 4,
      "mean": 0.0,
      "median": 0.0,
      "riserMean": 0.0,
      "fallerMean": 0.0,
      "brand": "4+ Nutrition",
      "max": 0.0
    }
  ],
  "risersByMonth": {
    "2026-06": 6,
    "2026-07": 12,
    "2026-08": 12,
    "2026-09": 10
  },
  "biggestDays": [
    [
      "2026-08-20",
      10
    ],
    [
      "2026-09-19",
      9
    ],
    [
      "2026-06-24",
      8
    ],
    [
      "2026-07-09",
      3
    ]
  ],
  "dayDetail": {
    "2026-08-20": {
      "stores": 2,
      "brands": {
        "Maximalium": 5,
        "Nutriversum": 3,
        "5 Stars": 2
      }
    },
    "2026-09-19": {
      "stores": 1,
      "brands": {
        "Maximalium": 7,
        "Skull Labs": 1,
        "QNT": 1
      }
    }
  },
  "crossStore": [
    {
      "brand": "Maximalium",
      "grams": 750,
      "pct": 6.7,
      "from": 2390,
      "to": 2550,
      "stores": 2
    },
    {
      "brand": "Maximalium",
      "grams": 2270,
      "pct": 6.1,
      "from": 5250,
      "to": 5570,
      "stores": 2
    },
    {
      "brand": "Maximalium",
      "grams": 4500,
      "pct": 2.2,
      "from": 8290,
      "to": 8470,
      "stores": 2
    },
    {
      "brand": "Skull Labs",
      "grams": 2000,
      "pct": 6.7,
      "from": 7490,
      "to": 7990,
      "stores": 2
    },
    {
      "brand": "Maximalium",
      "grams": 750,
      "pct": 12.5,
      "from": 3190,
      "to": 3590,
      "stores": 2
    }
  ],
  "biggestRises": [
    {
      "name": "Whey pro protein 1kg - Nutriversum",
      "brand": "Nutriversum",
      "from": 2880,
      "to": 3990,
      "pct": 38.5
    },
    {
      "name": "Gold Standard 100% Whey – Optimum Nutrition, 14, 29 i 73 porcije",
      "brand": "Optimum Nutrition",
      "from": 3490,
      "to": 4690,
      "pct": 34.4
    },
    {
      "name": "Nutriversum Whey Pro, 700g",
      "brand": "Nutriversum",
      "from": 2690,
      "to": 3490,
      "pct": 29.7
    },
    {
      "name": "Whey protein 3kg - 5Stars",
      "brand": "5 Stars",
      "from": 6790,
      "to": 8750,
      "pct": 28.9
    },
    {
      "name": "Amino Whey Hydro – The Nutrition, 30 i 92 porcije",
      "brand": "The Nutrition",
      "from": 2950,
      "to": 3700,
      "pct": 25.4
    },
    {
      "name": "PurePro ISO Pro – Nutriversum, 40 porcija",
      "brand": "Nutriversum",
      "from": 3590,
      "to": 4490,
      "pct": 25.1
    },
    {
      "name": "NUTRIVERSUM WHEY PRO, 2000g",
      "brand": "Nutriversum",
      "from": 5690,
      "to": 7100,
      "pct": 24.8
    },
    {
      "name": "ISO Pro (Izolat proteina surutke),1000 g",
      "brand": "Nutriversum",
      "from": 3690,
      "to": 4590,
      "pct": 24.4
    }
  ],
  "falls": [
    {
      "name": "Reflex Nutrition One Stop® Xtreme",
      "brand": "Reflex Nutrition",
      "from": 13490,
      "to": 9500,
      "pct": -29.6
    }
  ]
} as const;
